### ISSUE TITLE
When creating cobertura file, does not pick up individual files.

### ISSUE THREAD

**Issue by sbhanderi** [danielpalme/OpenCoverToCoberturaConverter#13]
Hi Daniel,

I run the 2 commands.
c:\Jenkins\workspace\WPLync-Regression>c:\Tools\ReportGenerator_2.5.6.0\ReportGenerator.exe -reports:LatestLogs/*/*Coverage.xml -reporttypes:Badges;Html;HtmlSummary -targetdir:CoverageReport

This command works correctly. Converting to HTML files.
The line -report:LatestLogs/*/*Coverage.xml finds all the individual opencover files ( there are many ) 

After that I run  OpenCoverToCoberturaConverter thinking it will find the openCover xml files in the same way.

c:\Jenkins\workspace\WPLync-Regression>c:\Tools\OpenCoverToCoberturaConverter.0.2.6.0\tools\OpenCoverToCoberturaConverter.exe -input:LatestLogs/*/*Coverage.xml -output:Cobertura.xml -sources:c:\Jenkins\workspace\WPLync-Regression 
Report does not exist: LatestLogs/*/*Coverage.xml

So it cannot find the openCover files.

Is there a solution to this at all ? Do I need to somehow merge all the opencover xml files together, or have a missed something ?

thanks

**Comment by danielpalme** [comment]
ReportGenerator supports wildcards in the path(s) and is able to process all the files matching that path.
OpenCoverToCoberturaConverter is only able to process a single file.

**Comment by sbhanderi** [comment]
Thanks daniel.
So is it possible to merge all the openCover xml files into 1 files ?

**Comment by danielpalme** [comment]
No, that's not possible.

**Comment by sbhanderi** [comment]
Thanks. I will close this, as question answered.

**Comment by gomaa86** [comment]
would be great if this feature added
