### ISSUE TITLE
Open Cover xml not getting converted to cobertura report

### ISSUE THREAD

**Issue by ronniekapoor** [danielpalme/OpenCoverToCoberturaConverter#14]
Hi I am using this library to convert open cover reports to cobertura report but the final report is not showing any coverage data.

I am attaching the example file which i am trying to convert . Please convert it into .xml format before trying.
[Coverage - Copy.txt](https://github.com/danielpalme/OpenCoverToCoberturaConverter/files/1186407/Coverage.-.Copy.txt)

The powershell command used to convert is as follows.

# open cover to cobertura report conversion
Start-Process "Path to OpenCoverToCoberturaConverter.exe" -Wait -ArgumentList "-oldstyle -input:""path to Coverage - Copy.xml"" -output:""path to Cobertura.xml"" -sources:""%*%"" "

can you please check why it is not getting the right coverage?

**Comment by danielpalme** [comment]
I don't know what output you would expect.

But perhaps you are simply missing the following command line argument:
_-includeGettersSetters:true_

**Comment by ronniekapoor** [comment]
hi daniel,

Thanks for the input. It worked. 

I have however a next problem of merging two or more cobertura.xml files together for single reporting. Is there any plugin or library which can help me do that? 

can you suggest something?

**Comment by danielpalme** [comment]
Perhaps you should try https://github.com/danielpalme/ReportGenerator
This tool supports merging several cobertura files and generates a HTML report.
