### ISSUE TITLE
The conversion result from a SQLCover Coverage.opencoverxml -input has zero coverage

### ISSUE THREAD

**Issue by lestephane** [danielpalme/OpenCoverToCoberturaConverter#18]
I'm trying to convert an SQLCover opencover report to a cobertura report.

The -input has definitely some coverage in it (4 sequence points):
```xml
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <Summary numSequencePoints="786" visitedSequencePoints="4" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0.508905854076147" branchCoverage="0.0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" />
...
```
The resulting -output does not:
```xml
<coverage line-rate="1" branch-rate="1" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0" complexity="0" version="0" timestamp="1522341259">
...
```
My command-line to convert does nothing fancy. I have a RunSqlCoverageTool.ps1 which calls out to SQLCover, then calls out to OpenCoverToCoberturaConverter.exe
```powershell
$sqlCoverPath = "$PSScriptRoot\Tools\SQLCover"
. $sqlCoverPath\SQLCover.ps1

$result = Get-CoverTSql "$sqlCoverPath\SQLCover.dll" "$connectionString" "<test db>" "EXEC [tSQLt].[RunAll]"

"$PSScriptRoot\..\packages\OpenCoverToCoberturaConverter.0.2.6.0\tools\OpenCoverToCoberturaConverter.exe" -input:.\Coverage.opencoverxml -output:.\Cobertura.xml -sources:$PSScriptRoot
```
I have found at least [one other report](https://codewithstyle.info/setting-up-coverage-reports-on-vsts-with-opencover/#comment-204) of the same behaviour.

Any pointer has to what might be causing this?

**Comment by danielpalme** [comment]
Without the OpenCover file it is hard to guess what goes wrong. Can you please send me the OpenCover report by email (danielpalme82@gmail.com)?

**Comment by lestephane** [comment]
Let me dig that up, sorry for the delay...

**Comment by danielpalme** [comment]
Thanks for your email. I will have a look at it within the next days.

**Comment by danielpalme** [comment]
If you use the command line parameter `-includeGettersSetters:true` it works as expected.  
In your case use the following command:
```
"$PSScriptRoot\..\packages\OpenCoverToCoberturaConverter.0.2.6.0\tools\OpenCoverToCoberturaConverter.exe" -input:.\Coverage.opencoverxml -output:.\Cobertura.xml -includeGettersSetters:true -sources:$PSScriptRoot
```

**Comment by danielpalme** [comment]
The stored procedures are marked as setters by SQLCover.
I think it makes sense to set the default of _-includeGettersSetters_ to `true`.

**Comment by lestephane** [comment]
@GoEddie: was it the intent of SQLCover's OpenCover export to mark the procedures as setters?

If @danielpalme changes its default, he might get a few angry customers that have started to rely on the old default of -includeGettersSetters:false

**Comment by GoEddie** [comment]
It is probably an oversight, what marks it as a setter in the open xml file?

- Why do you want corbatura support? If it is for vsts I have a version that creates enough info to get the vsts code coverage widget working
- Feel free to raise this over at the sqlcover repo

:)

Ed
