### ISSUE TITLE
Attribute skippedDueTo Not Used to Ignore Skipped Coverage

### ISSUE THREAD

**Issue by vellucci52** [danielpalme/OpenCoverToCoberturaConverter#19]
I have plenty of the following in my OpenCover results due to filtering out basic POCO's as part of my code coverage metric:
`<Module skippedDueTo="Filter" hash="...">`

Consequently, my line coverage is 10% and branch coverage is 7% in OpenCover, but my line coverage is 0.67% and branch coverage is 0% in the resulting Cobertura file. Please ignore all modules in the OpenCover results that have the skippedDueTo attribute when generating the Corbertura file, so the percentages align better.

Also, to be clear, I am leveraging [Cake](https://cakebuild.net/dsl/opencover/) with .NET Core, so I am not sure if this converter will work appropriately given that this requires OpenCover to be called with the `-oldStyle` flag.

Thank you.

**Comment by danielpalme** [comment]
Skipped elements are already filtered:
- https://github.com/danielpalme/OpenCoverToCoberturaConverter/blob/master/OpenCoverToCoberturaConverter/Converter.cs#L69
- https://github.com/danielpalme/OpenCoverToCoberturaConverter/blob/master/OpenCoverToCoberturaConverter/Converter.cs#L124
- https://github.com/danielpalme/OpenCoverToCoberturaConverter/blob/master/OpenCoverToCoberturaConverter/Converter.cs#L161
- https://github.com/danielpalme/OpenCoverToCoberturaConverter/blob/master/OpenCoverToCoberturaConverter/Converter.cs#L232

Can you supply a sample file if this does not work?

**Comment by vellucci52** [comment]
Examples of the two files appear in the zip below. I ran the converter via the PowerShell script that is also contained in the zip. The NuGet package is 0.3.1, and I just had the unit test project reference it, which allowed the script to reference it from the current user's NuGet directory.

[Examples.zip](https://github.com/danielpalme/OpenCoverToCoberturaConverter/files/1949274/Examples.zip)

**Comment by danielpalme** [comment]
Please try the new release:
https://www.nuget.org/packages/OpenCoverToCoberturaConverter/0.3.2

**Comment by vellucci52** [comment]
Much better. Thank you. This issue is resolved.
