### ISSUE TITLE
VSTS Extension

### ISSUE THREAD

**Issue by Thilas** [danielpalme/OpenCoverToCoberturaConverter#20]
Hi, have you thought about providing a VSTS extension for this great tool? It would be awesome to be able to use it directly inside a build pipeline. Thanks!

**Comment by danielpalme** [comment]
Good idea.
Not sure when I will find time to create an extension.

**Comment by Thilas** [comment]
I'll see but I might be able to create one on coming weeks if you don't. Let's stay in touch!

**Comment by Thilas** [comment]
I recently realized that ReportGenerator was one of your creations (thanks for these!) as well and since it now supports to generate Cobertura (and HtmlInline) reports, I am not sure I will create a VSTS extension for OpenCoverToCoberturaConverter. But I might create one for ReportGenerator. I'll let you know.

**Comment by danielpalme** [comment]
That was also my plan.
I want to create a _ReportGenerator_ extension for VSTS and if that works, I can create another one for _OpenCoverToCoberturaConverter_.

**Comment by Thilas** [comment]
That's great news! BTW, if you plan to work on a task for _ReportGenerator_, you can also include one for _OpenCoverToCoberturaConverter_: it makes sense to group both tasks in a single extension.

**Comment by danielpalme** [comment]
ReportGenerator is now available as an Azure DevOps extension:
https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator

_ReportGenerator_ has good support for _Cobertura_ format now, which makes _OpenCoverToCoberturaConverter_ a bit obsolete.

_ReportGenerator_ has the following advantages:

- Merging of several coverage files
- Supports several input and output formats

**Comment by Thilas** [comment]
Glad to read this, thanks! I'll give a try soon to this new extension of yours and let you know. I'm closing this issue.
