### ISSUE TITLE
Cobertura output is rendered as UTF-8 BOM

### ISSUE THREAD

**Issue by medianick** [danielpalme/OpenCoverToCoberturaConverter#23]
Because this utilizes XDocument.Save, it is creating files with a UTF-8 BOM encoding, which in turn causes problems with file utilities that do not expect a BOM on UTF-8 documents. Use of BOM is neither required nor recommended for UTF-8, according to the Unicode Standard (see [Wikipedia](https://en.wikipedia.org/wiki/Byte_order_mark#cite_note-4)).

StackOverflow has a technique for writing out files without this BOM: https://stackoverflow.com/questions/4942825/xdocument-saving-xml-to-file-without-bom

This is currently causing me issues with reading the Cobertura XML within a Jenkins pipeline, using XmlSlurper().

**Comment by danielpalme** [comment]
I just looked at a couple of Cobertura files generated by various tools (Cobertura, istanbul, Coverlet, altcover).
All of them contain a BOM.

If I change _OpenCoverToCoberturaConverter_ this may break other tools that rely on the VOM being present.

**Comment by medianick** [comment]
Perhaps it could be configured via switch? I have in the meantime come up with a workaround for my use case, which involves doing a replace of the `\uFEFF` if found in the XML data, prior to parsing it.

```
def coverageData = new XmlSlurper(false, false, true).parseText(coverageFile.replace("\uFEFF", ""))
```

In the above, `coverageFile` is a string containing the XML content as read from the file system (Jenkins workspace, in my case).

I'm happy to close this if it's too much of a potential breaking change for other integrations.

**Comment by danielpalme** [comment]
I would close this for now as you have a good work around for the problem.
