### ISSUE TITLE
Cobertura (in Jenkins) cannot show source code for cobertura report

### ISSUE THREAD

**Issue by JohnnyMLH** [danielpalme/OpenCoverToCoberturaConverter#5]
Hi Daniel,
I'd like to report a problem I found due to directory naming incompatibility " / vs \ ".
i have Jenkins so that the parameter passed to the OpenCoverToCoberturaConverter is like:
 d:/svn_path/library
The OpenCover.exe generates paths like this d:\svn_path\library.
When I now do OpenCoverToCoverturaConverter and pass as sources directory d:/svn_path/library, 
the cobertura plugin doesn't find the source code for the files.

I've fixed this problem now, by changing the source-code of the Converter.cs.
Would it be ok, for you to include it in your files as well?

-Method added to the Converter class:
         public static string _ConvertToWindowsPath(string path)
        {
           return path.Replace("/", "\\");
        }

- Method changed ConvertToCobertura
 public static XDocument ConvertToCobertura(XDocument openCoverReport, string sourcesDirectory)
        {
            if (openCoverReport == null)
            {
                throw new ArgumentNullException("openCoverReport");
            }
            //Line below added:
            sourcesDirectory = _ConvertToWindowsPath(sourcesDirectory);

            XDocument result = new XDocument(new XDeclaration("1.0", null, null), CreateRootElement(openCoverReport, sourcesDirectory));
            result.AddFirst(new XDocumentType("coverage", null, "http://cobertura.sourceforge.net/xml/coverage-04.dtd", null));

            return result;
        }

- Method changed CreateClassElement
....
            // First method is used to determine name of file (partial classes are not handled correctly)
            string fileName = firstMethodWithFileRef == null ? string.Empty : filesById[firstMethodWithFileRef.Element("FileRef").Attribute("uid").Value];
            //Line below added:
            fileName = _ConvertToWindowsPath(fileName);
            fileName = commonPrefix.Replace(fileName, string.Empty);
..

I hope this is enough detail for you.
If you have any problem with this please let me know.

Best regards,
Joao

**Comment by danielpalme** [comment]
Thanks for reporting this,
I will have a look at this within the next days.

**Comment by danielpalme** [comment]
I have commited your proposed changes (with some extra validation).
Please find new release here:
https://www.nuget.org/packages/OpenCoverToCoberturaConverter/0.2.2
