### ISSUE TITLE
Coverage for C# 4.5 Async methods is not working

### ISSUE THREAD

**Issue by JohnnyMLH** [danielpalme/OpenCoverToCoberturaConverter#6]
Hi Daniel,

the conversion of the OpenCover.XML into Cobertura.XML is not working properly for Async methods.
Since the other project ReportGenerator (https://github.com/danielpalme/ReportGenerator) is, I thought that is must be some kind of problem in the OpenCoverToCoberturaCoverter.

I've updated the converter.cs file (renamed it to png, so that I could upload it. So please download the PNG and rename it to .cs) (https://cloud.githubusercontent.com/assets/11866153/7196729/814a442a-e4d7-11e4-9659-fbc858e3978b.png)

It now works ok, but it is still not 100%, for it still shows that some branches are not covered 100%, althought it doesn't have any if or while.
The ReportGenerator can generate HTML properly (and gives the same kind of problem 3/4 branches coverted), so I guess that it is ok.

Could you please have a look and see if you agree with it?

Best regards,
Joao

**Comment by danielpalme** [comment]
Could you please provide me a sample cobertura XML?
I would like to compare the results myself.

**Comment by JohnnyMLH** [comment]
Hi Daniel,

thanks for responding.
I've attached an example input opencover XML (again with the PNG trick...) 
![input-opencover.xml](https://cloud.githubusercontent.com/assets/11866153/7198735/657b8476-e4ef-11e4-9a85-b31714cefef0.png)

The output for the change I made is:
![cobertura-output xml](https://cloud.githubusercontent.com/assets/11866153/7198847/1c2ffeea-e4f0-11e4-9a86-b71b2bc9ce9b.png)

Please notice that the ReportGenerator generates a "Green" line, and also writes "1 of 2 branches are covered".
I've also attached the complete source-code (VS project), so that you can see it.
The line in question contains only:
  await Task.Delay(100); 
in method:  public async Task<CompositeType> GetDataUsingDataContract(CompositeType composite)

![testcoverage zip](https://cloud.githubusercontent.com/assets/11866153/7198762/95173216-e4ef-11e4-94fa-c8bce31f1aaf.png)

**Comment by JohnnyMLH** [comment]
Thanks! :)

It is not 100% ready, but thanks for adding it :)
