### ISSUE TITLE
MSI-Installer

### ISSUE THREAD

**Issue by mubed** [danielpalme/OpenCoverToCoberturaConverter#8]
Isn't any MSI installer available for this tool? I have no NuGet and don't know how to use it.

**Comment by danielpalme** [comment]
Sorry but there is no MSI available.

NuGet is integrated into Visual Studio. So this should not be a problem.
http://docs.nuget.org/consume/package-manager-dialog

Visual Studio is available for free:
https://www.visualstudio.com/
